apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: strava-java-comments-pro
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: api.madastur.com
      http:
        paths:
          - path: /strava/comments
            backend:
              serviceName: strava-java-comments-svc-pro
              servicePort: 8082
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: strava-java-comments-svc-pro
  name: strava-java-comments-svc-pro
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
      name: strava-java-comments-svc-pro
  selector:
    app: strava-java-comments-pro
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strava-java-comments-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strava-java-comments-pro
  template:
    metadata:
      labels:
        app: strava-java-comments-pro
    spec:
      containers:
        - name: strava-java-comments-pre
          image: mpastorg/client-comments:$RELEASE.$BUILD_NUMBER
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            failureThreshold: 3
            periodSeconds: 60
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            failureThreshold: 3
            periodSeconds: 99
          volumeMounts:
            - name: cm-app-strava-vol
              mountPath: "/config"
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 50m
              memory: 512Mi
      nodeSelector:
        kubernetes.io/arch: amd64
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: cm-app-strava-vol
          configMap:
            name: cm-app-strava-pro-fc7tkb7g69
            items:
              - key: application.properties
                path: application.properties
