pipeline {
  agent any
  environment {
    ENV = 'default'
    RELEASE = '0.3'
    registry = "mpastorg/client-comments"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  stages {
      stage('prepare for kubernetes') {
        input {
            message "Introduce build number"
            parameters {
                string(name: 'MPGBUILD', defaultValue: '00', description: 'Deploy this build number:')
            }
        }
        steps{
          sh "sed 's/MPGENV/default/' strava-java-comments.yml > deplo_pro_1.yml"
          sh "sed 's/MPGRELEASE.MPGBUILD_NUMBER/$RELEASE.$MPGBUILD/' deplo_pro_1.yml > deplo_pro_2.yml"
        }
      }
        stage('SSH Into k8s Server') {
          steps{
            script{
                def remote = [:]
                remote.name = 'mpg4ras01'
                remote.host = 'mpg4ras01'
                remote.allowAnyHosts = true
                withCredentials([usernamePassword(credentialsId: 'mpgubumac01', usernameVariable: 'USERNAME'
                , passwordVariable: 'PASSWORD')])
                {
                    remote.user = "$USERNAME"
                    remote.password = "$PASSWORD"
                    sshPut remote: remote, from: 'deplo_pro_2.yml', into: '.'
                    sshCommand remote: remote, command: "kubectl apply -f deplo_pro_2.yml"
                    sshRemove remote: remote, path: 'deplo_pro_2.yml'
                }
            }
          }
        }
    }

}
