pipeline {
  agent any
  environment {
    ENV = 'pro'
    RELEASE = '0.2'
    CONFIGMAP = '5b94df246h'
    registry = "mpastorg/client-comments"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
    stage('Deploy on kubernetes') {
      steps {
          kubernetesDeploy(
              kubeconfigId: '1c99e9a6-3159-41f1-a7d3-2e4dbbe13455',
              configs: 'strava-java-comments.yml',
              enableConfigSubstitution: true
          )
      }
    }
  }
}
